# Set site parameters
SITE_NAME = 'GeoRegistry'
SITE_VERSION = '0.2'
# Set person parameters
USERNAME_LENGTH_MINIMUM = 6
USERNAME_LENGTH_MAXIMUM = 32
PASSWORD_LENGTH_MINIMUM = 6
PASSWORD_LENGTH_AVERAGE = 16
NICKNAME_LENGTH_MINIMUM = 3
NICKNAME_LENGTH_MAXIMUM = 32
EMAIL_LENGTH_MAXIMUM = 48
TICKET_LENGTH = 32
TICKET_LIFESPAN_IN_DAYS = 1
REJECTION_LIMIT = 3
MINUTES_OFFSET_DEFAULT = 240
KEY_LENGTH = 256
# Set tag parameters
TAG_LENGTH_MAXIMUM = 256
